import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/containers/Header";

const instrument_Sans = Instrument_Sans({ subsets: ["latin"], weight: ["600", "400"] });

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={instrument_Sans.className}>
        <Header />
        <main className="flex flex-wrap justify-center gap-8 container">
          {children}
        </main>
      </body>
    </html>
  );
}
